[package]
name = "rust_macro_hw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
macro_p = { path = "macro_p" }
